import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export default {
  basicsSidebar: [{ type: "autogenerated", dirName: "basics" }],
  administrationSidebar: [{ type: "autogenerated", dirName: "administration" }],
} satisfies SidebarsConfig;
